/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-08 09:20:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ContactUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Feedback - Online Train Reservation System</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"home.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Existing styles retained */\r\n");
      out.write("        @import url(\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap\");\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("		  margin: 0;\r\n");
      out.write("		  padding: 0;\r\n");
      out.write("		  box-sizing: border-box;\r\n");
      out.write("		  font-family: \"Open Sans\", sans-serif;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 0 10px;\r\n");
      out.write("  			background: linear-gradient(to bottom, #175d69 23%, #330c43 95%);\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wrapper {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.5);\r\n");
      out.write("            backdrop-filter: blur(8px);\r\n");
      out.write("            -webkit-backdrop-filter: blur(8px);\r\n");
      out.write("    		margin-top: 80px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* General styles */\r\n");
      out.write(".input-field {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin: 20px 0;\r\n");
      out.write("    padding: 3px;\r\n");
      out.write("    background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    transition: background 0.3s ease;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-field label {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 10px;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("    color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    pointer-events: none;\r\n");
      out.write("    transition: 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style adjustments for the input, textarea, and select */\r\n");
      out.write(".input-field input,\r\n");
      out.write(".input-field textarea,\r\n");
      out.write(".input-field select {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Textarea specific styles */\r\n");
      out.write(".input-field textarea {\r\n");
      out.write("    height: 120px;\r\n");
      out.write("    resize: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Focus styles */\r\n");
      out.write(".input-field input:focus,\r\n");
      out.write(".input-field textarea:focus,\r\n");
      out.write(".input-field select:focus {\r\n");
      out.write("    background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("    box-shadow: 0 0 5px rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Styles to keep label elevated */\r\n");
      out.write(".input-field input:focus ~ label,\r\n");
      out.write(".input-field input:valid ~ label,\r\n");
      out.write(".input-field textarea:focus ~ label,\r\n");
      out.write(".input-field textarea:valid ~ label,\r\n");
      out.write(".input-field select:focus ~ label,\r\n");
      out.write(".input-field select:valid ~ label,\r\n");
      out.write(".input-field input:not(:placeholder-shown) ~ label,\r\n");
      out.write(".input-field textarea:not(:placeholder-shown) ~ label,\r\n");
      out.write(".input-field select:not(:placeholder-shown) ~ label {\r\n");
      out.write("    top: -10px;\r\n");
      out.write("    font-size: 0.85rem;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-field select option {\r\n");
      out.write("    background: rgba(0, 0, 0, 0.9); /* Darker background for options */\r\n");
      out.write("    color: #fff; /* Text color for options */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Button styles */\r\n");
      out.write("button {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 12px;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    color: #4e54c8;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("    background-color: #8f94fb;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    box-shadow: 0 4px 20px rgba(143, 148, 251, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header section with navigation -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <h2 class=\"logo\"><a href=\"#\">ExpressReserve</a></h2>\r\n");
      out.write("            <input type=\"checkbox\" id=\"menu-toggle\" />\r\n");
      out.write("            <label for=\"menu-toggle\" id=\"hamburger-btn\">\r\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\">\r\n");
      out.write("                    <path d=\"M3 12h18M3 6h18M3 18h18\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>\r\n");
      out.write("                </svg>\r\n");
      out.write("            </label>\r\n");
      out.write("            <ul class=\"links\">\r\n");
      out.write("                <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">Services</a></li>\r\n");
      out.write("                <li><a href=\"#\">Book Now</a></li>\r\n");
      out.write("                <li><a href=\"ContactUs.jsp\">Contact Us</a></li>\r\n");
      out.write("          		<li><a href=\"Account.jsp\">Account</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"buttons\">\r\n");
      out.write("	          <a href=\"login.jsp\" class=\"signup\">Sign In</a>\r\n");
      out.write("	          <a href=\"#\" class=\"signup\">Admin</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Middle section for feedback form -->\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <h2>Submit Feedback or Complaint</h2>\r\n");
      out.write("        <form action=\"ContactUs\" method=\"post\">\r\n");
      out.write("		    <div class=\"input-field\">\r\n");
      out.write("			    <input type=\"text\" name=\"PassengerName\" required autocomplete=\"off\" value=\"");
      out.print( session.getAttribute("username") != null ? session.getAttribute("username") : "" );
      out.write("\" readonly>\r\n");
      out.write("			    <label>Passenger Name</label>\r\n");
      out.write("			</div>\r\n");
      out.write("		    <div class=\"input-field\">\r\n");
      out.write("		    	<input type=\"text\" name=\"PassengerEmail\" required autocomplete=\"off\" value=\"");
      out.print( session.getAttribute("email") != null ? session.getAttribute("email") : "" );
      out.write("\" readonly>\r\n");
      out.write("			    <label>Passenger Name</label>\r\n");
      out.write("		    </div>\r\n");
      out.write("		    <div class=\"input-field\">\r\n");
      out.write("		        <select id=\"complaintType\" name=\"complaintType\" required>\r\n");
      out.write("		            <option value=\"\">Select Complaint Type</option>\r\n");
      out.write("		            <option value=\"Train Services\">Train Services</option>\r\n");
      out.write("		            <option value=\"Station Facilities\">Station Facilities</option>\r\n");
      out.write("		            <option value=\"Staff Behavior\">Staff Behavior</option>\r\n");
      out.write("		        </select>\r\n");
      out.write("		        <label>Complaint Type</label>\r\n");
      out.write("		    </div>\r\n");
      out.write("		    <div class=\"input-field\">\r\n");
      out.write("		        <textarea id=\"complaintDescription\" name=\"Feedback\" required></textarea>\r\n");
      out.write("		        <label>Complaint Description</label>\r\n");
      out.write("		    </div>\r\n");
      out.write("		    <button type=\"submit\">Submit</button>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
