/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-08 16:40:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Login - Online Train Reservation System</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"home.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Importing Google font - Open Sans */\r\n");
      out.write("        @import url(\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap\");\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("		  margin: 0;\r\n");
      out.write("		  padding: 0;\r\n");
      out.write("		  box-sizing: border-box;\r\n");
      out.write("		  font-family: \"Open Sans\", sans-serif;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 0 10px;\r\n");
      out.write("  			background: linear-gradient(to bottom, #175d69 23%, #330c43 95%);\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            z-index: 1; /* Ensure header is on top */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 20px 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .logo a {\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            gap: 35px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .links a {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            transition: 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .links a:hover {\r\n");
      out.write("            color: #47b2e4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .buttons a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            padding: 15px 0;\r\n");
      out.write("            transition: 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .buttons a:not(:last-child) {\r\n");
      out.write("            margin-right: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .buttons .signin:hover {\r\n");
      out.write("            color: #47b2e4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .buttons .signup {\r\n");
      out.write("            border: 1px solid #fff;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border-radius: 0.375rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .buttons .signup:hover {\r\n");
      out.write("            background-color: #47b2e4;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wrapper {\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.5);\r\n");
      out.write("            backdrop-filter: blur(8px);\r\n");
      out.write("            -webkit-backdrop-filter: blur(8px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-field {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            border-bottom: 2px solid #ccc;\r\n");
      out.write("            margin: 15px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-field label {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("            transition: 0.15s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-field input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            border: none;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-field input:focus~label,\r\n");
      out.write("        .input-field input:valid~label {\r\n");
      out.write("            font-size: 0.8rem;\r\n");
      out.write("            top: 10px;\r\n");
      out.write("            transform: translateY(-120%);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .forget {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            margin: 25px 0 35px 0;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #remember {\r\n");
      out.write("            accent-color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .forget label {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .forget label p {\r\n");
      out.write("            margin-left: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wrapper a {\r\n");
      out.write("            color: #efefef;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wrapper a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            color: #000;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            border: 2px solid transparent;\r\n");
      out.write("            transition: 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-color: #fff;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hamburger menu styles */\r\n");
      out.write("        #menu-toggle {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #hamburger-btn {\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            display: none;\r\n");
      out.write("            order: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media screen and (max-width: 1023px) {\r\n");
      out.write("            .navbar .logo a {\r\n");
      out.write("                font-size: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .links {\r\n");
      out.write("                position: fixed;\r\n");
      out.write("                left: -100%;\r\n");
      out.write("                top: 75px;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 100vh;\r\n");
      out.write("                padding-top: 50px;\r\n");
      out.write("                background: #175d69;\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                transition: 0.3s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .navbar #menu-toggle:checked ~ .links {\r\n");
      out.write("                left: 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .navbar #hamburger-btn {\r\n");
      out.write("                display: block;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .header .buttons {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <h2 class=\"logo\"><a href=\"#\">ExpressReserve</a></h2>\r\n");
      out.write("            <input type=\"checkbox\" id=\"menu-toggle\" />\r\n");
      out.write("            <label for=\"menu-toggle\" id=\"hamburger-btn\">\r\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\">\r\n");
      out.write("                    <path d=\"M3 12h18M3 6h18M3 18h18\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>\r\n");
      out.write("                </svg>\r\n");
      out.write("            </label>\r\n");
      out.write("            <ul class=\"links\">\r\n");
      out.write("                <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">Services</a></li>\r\n");
      out.write("                <li><a href=\"#\">Book Now</a></li>\r\n");
      out.write("                <li><a href=\"ContactUs.jsp\">FeedBack</a></li>\r\n");
      out.write("                <li><a href=\"account.html\">Account</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"buttons\">\r\n");
      out.write("	          <a href=\"login.jsp\" class=\"signup\">Sign In</a>\r\n");
      out.write("	          <a href=\"AdminLogin.jsp\" class=\"signup\">Admin</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <h2>Login to Your Account</h2>\r\n");
      out.write("        <form action=\"Login\" method=\"post\">\r\n");
      out.write("            <div class=\"input-field\">\r\n");
      out.write("                <input type=\"text\" name=\"Username\" required autocomplete=\"off\">\r\n");
      out.write("                <label>Username</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-field\">\r\n");
      out.write("                <input type=\"password\" name=\"Password\" required>\r\n");
      out.write("                <label>Password</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\">Login</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"forget\">\r\n");
      out.write("            <a href=\"#\">Forgot your password?</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"register\">New to Train Service? <a href=\"#\">Register here</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
